### ISSUE TITLE
Remove hardcoded path

### ISSUE THREAD

**Issue by domoritz** [leibatt/scalable-vega#10]
https://github.com/leibatt/scalable-vega/blob/026c28fa8a4ba539089161d35f2df4db6ec84caa/duckdb.config.json#L3

**Comment by JunranY** [comment]
https://github.com/leibatt/scalable-vega/commit/04481f1c634c21832fcd66630fa4427d440c883b#diff-96f807c1bd120e0f9e7240c0f3561ecff9fb006567e04e0cb3826dc56dadf8e3
