### ISSUE TITLE
Remove html from readme

### ISSUE THREAD

**Issue by domoritz** [leibatt/scalable-vega#17]
https://github.com/leibatt/scalable-vega/blob/master/README.md should be cleaned up

**Comment by domoritz** [comment]
this is not done

<img width="1300" alt="Screen Shot 2021-03-24 at 12 16 38" src="https://user-images.githubusercontent.com/589034/112370559-ca311a80-8c9a-11eb-902c-3c886afe80db.png">

**Comment by SaiArrow** [comment]
Oh I haven't pushed the updated file, will do it now
