### ISSUE TITLE
Glitch after demo vega spec 

### ISSUE THREAD

**Issue by joos2010kj** [leibatt/scalable-vega#46]
Pressing "Demo vega spec " button does do the job, but the website no longer gets updated if I make changes by uploading a different sample data.

**Comment by JunranY** [comment]
Running the histogram-extent example generate the above error because of how the extent transform was handled.
problem resulted from "vega-transform-db" packages. adding the Object prototype function messed with the rendering code in Vega. 
fixed in its 1.0.8 version.
