### ISSUE TITLE
push rewrites to the specification level rather than the instantiated graph level

### ISSUE THREAD

**Issue by leibatt** [leibatt/scalable-vega#6]
Currently, the code rewrites nodes in the instantiated Vega dataflow graph, which could fail if changes are made to the graph generation code. In the future, we should instead perform rewrites on the dataflow specification, rather than the instantiated graph, to make the solution resilient to updates to Vega in the future.

**Comment by JunranY** [comment]
We tried on specification level but later switched back to graph level to keep the structure.
